baseURL = "https://willemdek11.github.io/"
languageCode = "en-us"
title = "Hugo Profile"
theme = "hugo-profile"
paginate = 3
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe = true

[menus]
  [[menus.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog posts"
    url = "/blogs"
    weight = 1

  [[menus.main]]
    identifier = "gallery"
    name = "Gallery"
    title = "Blog posts"
    url = "/gallery"
    weight = 2

[params]
  title = "Hugo Profile"
  description = "Text about my cool site"
  favicon = "/fav.png"
  useBootstrapCDN = false
  mathjax = false
  animate = true

[params.theme]
  # disableThemeToggle = true
  # defaultTheme = "light" # dark

[params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

[params.navbar]
  align = "ms-auto"
  brandName = "Hugo Profile"
  disableSearch = false

  [params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

  enableSeparator = false

[params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Isabella."
  subtitle = "I build things for the web"
  content = "A passionate web app developer. I tend to make use of modern web technologies to build websites that look great, feel fantastic, and function correctly."
  image = "/images/hero.svg"

  [params.hero.bottomImage]
    enable = true

  [params.hero.button]
    enable = true
    name = "Resume"
    url = "#"
    download = true
    newPage = false

  [[params.hero.socialLinks.fontAwesomeIcons]]
    icon = "fab fa-github"
    url = "https://example.com"

  [[params.hero.socialLinks.fontAwesomeIcons]]
    icon = "fab fa-x-twitter"
    url = "https://example.com"

  [[params.hero.socialLinks.customIcons]]
    icon = "/fav.png"
    url = "https://example.com"

[params.about]
  enable = true
  title = "About Me"
  image = "/images/me.png"
  content = """
  I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA.

  I am currently working on a project that will be used to help people find the best way to get around the city.
  """

  [params.about.skills]
    enable = true
    title = "Here are a few technologies I've been working with recently:"
    items = ["HTML", "CSS", "JavaScript", "React", "Node", "Express"]

# Add other sections similarly...
